/**
 * Web: fetch the dataset instead of bundling it.
 *
 * `require`ing parking.json makes Metro inline 78,346 streets into the JS
 * bundle as object literals, which barely compresses — that shape measured
 * 25.85 MB brotli on the live site, against 3.5 MB for the same data as plain
 * JSON. A PWA pays that on every cold launch, so the files are served static
 * and fetched here.
 *
 * Split in two on purpose: the streets that carry rules are 0.7 MB gzipped and
 * are the whole point of the app, so they load first and the map is usable.
 * The 62,863 "no published data" streets are 2.8 MB and only draw as a grey
 * base network, so they arrive afterwards without holding anything up.
 *
 * Generated by scripts/split-parking-data.mjs at build time.
 */
import type { ParkingCollection, StreetFeature } from './types';

type Meta = ParkingCollection['metadata'];

async function getJSON<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return (await res.json()) as T;
}

export async function loadClassified(): Promise<{ features: StreetFeature[]; metadata: Meta }> {
  const [meta, cls] = await Promise.all([
    getJSON<{ metadata: Meta }>('/data/parking-meta.json'),
    getJSON<{ features: StreetFeature[] }>('/data/parking-classified.json'),
  ]);
  return { features: cls.features, metadata: meta.metadata };
}

export async function loadUnknown(): Promise<StreetFeature[]> {
  const unk = await getJSON<{ features: StreetFeature[] }>('/data/parking-unknown.json');
  return unk.features;
}
